config/routes.rb
Rails.application.routes.draw do
  
resources :tasks
  resources :users
  resource :sessions
  resources :profiles
  get 'users/:id' => 'users#show'

  root 'sessions#new'

end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps
  

  field :name, type: String
  field :priority, type: Integer
  field :deadline, type: Time
  field :is_completed, type: Mongoid::Boolean
  field :already_tallied, type: Mongoid::Boolean, default: false
  field :points, type:Integer, default: 0


  # validates_inclusion_of :transmission, in:["auto","manual"]
  # validates :year, numericality: { less_than_or_equal_to: 2014, greater_than_or_equal_to: 1900}na
  # validates_presence_of :name, :model, :year, :price, :transmission, message: "missing a field"

  # field :task_completed, type: Mongoid:: Boolean


  # field :work, type: Mongoid::Boolean
  # field :sleep, type: Mongoid::Boolean
  def time
    deadline
  end

  def time=(value)
    raise value.inspect
    deadline = (Time.new(deadline.year, deadline.month, deadline.day, time.hour, time.minute) + 7.hours)
  end
    
  embedded_in :user
end 

app/models/user.rb
require "bcrypt"
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :zipcode, type: Integer
  field :level, type: Integer, default: 0
  field :points, type: Integer, default: 5000


  #field :image, type: Image

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end


  embeds_many :tasks

  def tally_points
    self.tasks.each do |task|
      if task.deadline > Time.now && task.already_tallied == false
        point_change = 0
        if task.is_completed && task.already_tallied == false
          if task.priority == 1
            point_change = 1000
          elsif task.priority == 2
            point_change = 700
          elsif task.priority == 3
            point_change = 500
          # task.is_completed.push
        else
          point_change = -700        
        end
        # task already tallied
        task.already_tallied = true
        self.points += point_change
        task.update(points: point_change)
        task.user.save
      end
    end

    self.save
  end 


  def level_up
    self.points.each do |point|
      if points == 3000
          self.level += 1 && self.points = 0
        end
      end

  # def priority_points
  #   self.priority.each do |p|
  #     if p = 1
    







  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   include ApplicationHelper  

   	helper_method :greeting_time

     def authenticate_user
    if !self.current_user
      redirect_to new_sessions_path
    end
  end

     def greeting_time
    if (Time.now.hour >= 05) && (Time.now.hour < 12) 
        @greeting = "Good morning, "
    elsif (Time.now.hour >= 12) && (Time.now.hour < 18)
        @greeting = "Good afternoon, "
    elsif (Time.now.hour >= 18) || (Time.now.hour < 05) 
        @greeting = "Good evening, "
    end
 end

    def AM_PM
      if (Time.now.hour >= 0) && (Time.now.hour <12)
        @am_pm = "AM"
      else
        @am_pm = "PM"
      end
    end 
  
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
end

app/controllers/points_controller.rb
class PointsController < ApplicationController

	

# 	def tasks_completed
# 	if @user.task.each == false
# 		then user.points -= 500
# 	else
# 		then user.points += 700

# 	def level_up
# 		if @user.points >= 3000
# 			@user.level += 1 && @user.points (reset to zero)
#   end

#   


# end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id.to_s
      redirect_to @user
    end

  end

  def destroy
    session.delete(:remember_token)
    redirect_to tasks_path
  end

end

app/controllers/tasks_controller.rb
# class TasksController < ApplicationController
# 	def new
# 		@tasks = Task.all
# 	end

# end

class TasksController < ApplicationController

	before_action :authenticate_user

	def index
    @show_all = params[:show_all]

    if @show_all == 'true'
      @add = "Here are all of your tasks." 
      @tasks = current_user.tasks.order_by(:date.asc, :priority.asc, :time.asc)
      @show_all = true
    else
      @tasks = current_user.tasks.order_by(:date.asc, :priority.asc, :time.asc)
      @show_uncompletes = true
    end
  end

  def custom
    raise params.inspect
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def new
    # if current_user
      @task = Task.new
    # else
    #   redirect_to new_auth_path
  end

  ###### EDIT THIS PART! 
  def edit
  	@task = current_user.tasks.find(params[:id])
  end

  def create
	  @task = current_user.tasks.new(task_params)
      t=params[:task]
    @task.deadline = Time.new(t["deadline(1i)"], t["deadline(2i)"], t["deadline(3i)"], t["time(4i)"], t["time(5i)"])
    if @task.save
			redirect_to tasks_path, notice: 'Your task has been submitted. Do work, son.'
    else
      render action: 'new'
    end
  end



  def update
  	@task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Your task was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
	  @task = current_user.tasks.find(params[:id])
    # raise @task.user.id.to_s
    
    @task.user.points-=@task.points
    @task.delete
    current_user.save
    if current_user.points
		  redirect_to tasks_url
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :priority,  :is_completed)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      @users = User.all

  end

  def custom
    raise params.inspect
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
      @user = User.find(params[:id])
      @user.tally_points
         respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have signed up successfully"
      redirect_to tasks_path
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
#  	raise session[:remember_token].inspect
#	session[:remember_token] = nil
    @current_user ||= session[:remember_token] && User.find(session[:remember_token])
  end


  def authenticate_user
    if !current_user
      redirect_to new_sessions_path
    end
  end

end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_file1.html.erb
/* This is file 1. */

app/views/layouts/_file2.html.erb
/* This is file 2. */

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alfie</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Hello, I'm Alfie. </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "View Tasks", tasks_path %></li>
        <li><%= link_to "New Task", new_task_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Sign In", new_sessions_path %></li>
        <% else %>
          <li>Hello, <%= current_user.name.capitalize %>.</li>
          <li><%= link_to "Your Profile", user_path(current_user) %></li>
          <li><%= link_to "Sign Out", sessions_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid">
  
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>
</div>

</body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit your task?</h1>
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="box5">
 <div class="field_a">
  <div class = "box_text1">
    <%= f.label "What's your task?"%><br>
    <div class = "formfont">
    <%= f.text_field :name %>
    <a href="#box6"><div id="arrow"></div></a>
  </div>

    <div id="field_b ">
    <div id="box6">
      <div class = "box_text1">
    <%= f.label "Priority Level" %><br>
    <div class ="formfont">
    <%= f.number_field :priority %>
    <a href="#box7"><div id="arrow"></div></a>
  </div>
</div>
  </div>

    <div id="box7">
    <div class="field_c">
      <div class = "box_text1">
    <%= f.label "When is it due?" %><br>
    <%= f.date_select :deadline %>
    <a href="#box8"><div id="arrow"></div></a>
  </div>
</div>

    <div id="box8">
    <div class="field_d">
      <div class = "box_text1">
    <%= f.label "What time would you like to schedule this in?" %><br>
    <%= f.time_select :time%>
    <a href="#box9"><div id="arrow"></div></a>
  </div>
</div>

  <div class="field_e ">
    <div class = "box_text2">
    <%= f.label "Did you already finish this?" %><br>
    <%= f.check_box :is_completed %>
    <a href="#actions"><div id="arrow"></div></a>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

<br>

app/views/tasks/index.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<div class = "box1">
  <div class = "box_text1a">
    <% if @show_uncompletes %>

      <h1>- Your current tasks. -</h1>

      <div class = "formfont">
      <table class=".table table-hover bordered">
        
        <div class="row">
          <ul class='list-group'>
            <% @tasks.each do |task| %>
              <% if !task.is_completed %>
                  <div class = "row">
                     <div class="col-xs-2">
                      <%= task.is_completed %>
                    </div>
                      <div class="col-xs-2">
                      <%= task.priority %>
                    </div>
                      <div class="col-xs-2">
                      <%= task.name %>
                    </div>
                      <div class="col-xs-2">
                      <%= task.deadline %>
                    </div>
                      <span class="links">
                        <%= link_to 'Edit', edit_task_path(task) %>
                        <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </span>
                  </li>
                </div>
              </div>
              <% end %>
            <% end %>
          </ul>
        </div>
      </table>
    <% end %>




<br>

<h1><%= @add %></h1>

<% if @show_all %>
  <ul class='list-group'>
    <% @tasks.each do |task| %>
        <li class="list-group-item">
          <%= task.is_completed %>
          <%= task.priority %>
          <%= task.name %>
          <%= task.deadline %>
     
          
          <span class="links">
            <%= link_to 'Edit', edit_task_path(task) %>
            <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          </li>
        <% end %>
      </ul>
      <% end %>

    <%= link_to 'New Task', new_task_path, class: "button"%>
    <br>
    <br>
    Would you like to see all of your items, included the ones you finished?
    <br>
    <div>

    <div class="btn-group">
      <%= link_to 'SHOW EVERYTHING', tasks_path(show_all: "true"), class: 'btn btn-primary' %>
      <%= link_to 'SHOW TO-DOS', tasks_path, class: 'btn btn-primary' %>
    </div>
<!-- adds ? -->
    </div>
      <div class="rowheader"> <!-- transform:rotate(0deg);" data-500="background-color:rgb(255,0,0);transform:rotate(360deg);"> -->
<!--   <div id="titleb"><h1 class="header"> G O O D  <span class="title">M O R N I N G ! </span></h1></div> -->
      </div>
</div>
  </div>
</div>
</div>


</div>

app/views/tasks/new.html.erb
<html>
<head>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="http://www.seanmccambridge.com/tubular/js/jquery.tubular.1.0.js"></script>
  <script>

$(document).ready(function(){
  $('a[href="#box5"]').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname) {
      var $target = $(this.hash);
      $target = $target.length && $target
      || $('[name=' + this.hash.slice(1) +']');
      if ($target.length) {
        var targetOffset = $target.offset().top;
        $('html,body')
        .animate({scrollTop: targetOffset}, 1000);
       return false;
      }
    }
  });
});

$(document).ready(function(){
  $('a[href="#box7"]').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname) {
      var $target = $(this.hash);
      $target = $target.length && $target
      || $('[name=' + this.hash.slice(1) +']');
      if ($target.length) {
        var targetOffset = $target.offset().top;
        $('html,body')
        .animate({scrollTop: targetOffset}, 1000);
       return false;
      }
    }
  });
});

$(document).ready(function(){
  $('a[href="#box8"]').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname) {
      var $target = $(this.hash);
      $target = $target.length && $target
      || $('[name=' + this.hash.slice(1) +']');
      if ($target.length) {
        var targetOffset = $target.offset().top;
        $('html,body')
        .animate({scrollTop: targetOffset}, 1000);
       return false;
      }
    }
  });
});

$(document).ready(function(){
  $('a[href="#box6"]').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname) {
      var $target = $(this.hash);
      $target = $target.length && $target
      || $('[name=' + this.hash.slice(1) +']');
      if ($target.length) {
        var targetOffset = $target.offset().top;
        $('html,body')
        .animate({scrollTop: targetOffset}, 1000);
       return false;
      }
    }
  });
});

$(document).ready(function(){
  $('a[href="#field_a"]').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname) {
      var $target = $(this.hash);
      $target = $target.length && $target
      || $('[name=' + this.hash.slice(1) +']');
      if ($target.length) {
        var targetOffset = $target.offset().top;
        $('html,body')
        .animate({scrollTop: targetOffset}, 1000);
       return false;
      }
    }
  });
});

$('button').click(function() {
   $('div').slideToggle(); 
});

</script>

</head>

<div class="task_bg">

<div class = "box1">
<div class = "box_text1a">

<h2>Would you like to <br />
<h1> add a new task ?</h1> </h2>
<a href="#field_a"><div id="arrow"></div></a>
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <a href="#field_b"><div id="arrow"></div></a>
      </div>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
</div>

<div class="blurred 2">

 <div id="field_a">
 

  <div id="box4">
     <div class = "box_text1">
    <%= f.label "What's your task?"%><br>
    <div class = "formfont">
    <%= f.text_field :name %>
    <a href="#box5"><div id="arrow"></div></a>
  </div>
</div>
</div>
</div>

  </div>
  <div id="field_b ">
    <div id="box5">
      <div class = "box_text1">
    <%= f.label "Priority Level" %><br>
    <div class ="formfont">
    <%= f.number_field :priority %>
    <a href="#box6"><div id="arrow"></div></a>
  </div>
</div>
  </div>
  <div id = "box6">
    <div class = "box_text1">
    <div class="field_c ">
    <%= f.label "When is it due?" %><br>
    <%= f.date_select :deadline %>
    <a href="#box7"><div id="arrow"></div></a>
  </div>
</div>
<div id = "box7">
  <div class = "box_text1">
    <div class="field_d ">
    <%= f.label "What time are you doing it?" %><br>
    <%= f.time_select :time%>
    <a href="#box8"><div id="arrow"></div></a>
  </div>
</div>
</div>
  <div id = "box8">
    <div class = "box_text1">
  <div class="field_e">
    <%= f.label "Already done?" %><br>
    <%= f.check_box :is_completed %>
  </div>
</div>
  <div class="actions">
    <div class = "formfont">
    <%= f.submit %>
  </div>
  </div>
  </div>
  </div>
<% end %>

<br><br>
</div>
<!-- Params hash is: <%= params %> -->
</html>

app/views/tasks/show.html.erb
<h1>SHOW :)</h1>
<h3>Here are today's tasks. </h3>

<h3>You have <%= @task.name.count %> tasks to complete. </h3>

<%= @task.name.each do |t| %>
	<li> <%= t.name %> </li>
	<h3>PRIORITY: <%= @t.priority %></h3>
	<h3>DATE: <%= @t.date %></h3>
	<h3>COMPLETED: <%= @t.is_completed %></h3>
<% end %>




  

 

app/views/users/edit.html.erb
<h1>Would you like to edit your profile?</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class = "formfont">
  <div class="field">
    <%= f.label "Your name is:"%><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "I will e-mail you at  " %><br>
    <%= f.number_field :email %>
  </div>
    <div class="field">
    <%= f.label "Your current location (zip code) is" %><br>
    <%= f.number_field :zipcode %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

<br>

app/views/users/index.html.erb
<%= @users %>

<ul class='list-group'>
    <% @users.each do |user| %>
        <li class="list-group-item">
          <h1> Here are all of my users. </h1>
          <%= user.name %>
        </li>
        <li class="list-group-item">
          <%= user.tasks.each do |task| %>
          	<% task.is_completed  %>
          <% end %>
        </li>
    <% end %>

app/views/users/new.html.erb
<div class="box_text1a">

<h1>Hello, I'm Alfie. </h1> 
	<h4>Are you a new user?</h4>

<div class="signup_container">
	
<%= form_for @user do |f| %>
  Name: <div class = "formfont"> <%= f.text_field :name %> <br /> </div>
  Email: <div class = "formfont"> <%= f.text_field :email %> <br /> </div>
  Password: <div class = "formfont"> <%= f.password_field :password %> </div>
  <br />
  
  <%= f.submit %>
</div>
 </div>
</div>
<% end %>

app/views/users/show.html.erb
<html>
<head>
	
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script src="http://www.seanmccambridge.com/tubular/js/jquery.tubular.1.0.js"></script>
	<script src="dropit.js"></script>
	<script> 

$(document).ready(function(){
  $('a[href="#box2"]').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname) {
      var $target = $(this.hash);
      $target = $target.length && $target
      || $('[name=' + this.hash.slice(1) +']');
      if ($target.length) {
        var targetOffset = $target.offset().top;
        $('html,body')
        .animate({scrollTop: targetOffset}, 1000);
       return false;
      }
    }
  });
});

$(document).ready(function(){
  $('a[href="#box3"]').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
    && location.hostname == this.hostname) {
      var $target = $(this.hash);
      $target = $target.length && $target
      || $('[name=' + this.hash.slice(1) +']');
      if ($target.length) {
        var targetOffset = $target.offset().top;
        $('html,body')
        .animate({scrollTop: targetOffset}, 1000);
       return false;
      }
    }
  });
});

</script>

</head>

<div class = "box1">
	<div class = "box_text1">
	<h1><%= greeting_time %> <%= @user.name.capitalize %>. </h4>
	</h1>
	<!-- <h1> <%= (Time.now.hour) %12 %>:<%= (Time.now.min) %> </h1> -->
	<h1> <%= Time.now.strftime("%l:%M %p") %> </h1>
	<h3> <%= Time.now.month %>.<%= Time.now.day %>.<%= Time.now.year%></h3>
	<a href="#box2"><div id="arrow"></div></a>
</div>


</div> 

<div id = "box2"> 
	<div class = "box_text2">
	<h4> You have </h4> <h1> <%= @user.tasks.count %> </h1> <h4> tasks left to complete. </h4>
	<a href="#box3"><div id="arrow"></div></a>
</div>
</div>


<div id = "box3">
	<div class = "box_text3">

	<h3> You have </h3> <h1><%= @user.points %> </h1> <h3>  points. </h3>
	<a href="#box1ls"><div id="arrow"></div></a>
</div>
</div>

<%= link_to "Your Profile", edit_user_path(current_user) %>

<%= render partial: "layouts/file1" %>
<%= render partial: "layouts/file2" %>

</html>

<!-- time now -> 


	, <%= @user.name %> :)</h1> ... NEED TO FIX DUE DATE/PRIORITY SORTING... JQUERY CALENDAR
<h1> You are level <%= @user.level %> </h1>
<h1> You have <%= @user.points %> points. </h1>
<h1> You have <%= @user.tasks.count %> tasks. </h1>
<h3>TASKS <%= @user.tasks %></h3>
<h3>PRIORITY: <%= @task %></h3>
<h3>DATE: <%= @task %></h3>
<h3>COMPLETED: <%= @task %></h3>



<%= link_to "Edit", edit_user_path(@user), class: 'btn btn-primary' %>